/*
 * This source file was generated by the Gradle 'init' task
 */
package org.potato;

import org.potato.core.logging.Logger;
import org.potato.core.logging.Logger.LogClassType;

public class Main {
    private static final Logger logger = new Logger(Main.class, LogClassType.Master);

    public static void main(String[] args) {
        logger.error("Error test");
        logger.warn("Warning Test");
        logger.debug("Debug test");
        logger.info("Info test");
    }
}
